<?php
$pageTitle = "View Report";
require_once __DIR__ . '/../config/auth.php';
requireAdmin();

$id = (int)($_GET['id'] ?? 0);
if (!$id) {
    header("Location: performance_report.php");
    exit;
}

$stmt = $conn->prepare("SELECT pr.*, u.name as generated_by_name FROM performance_reports pr LEFT JOIN users u ON u.id = pr.generated_by WHERE pr.id = ?");
$stmt->bind_param("i", $id);
$stmt->execute();
$report = $stmt->get_result()->fetch_assoc();
$stmt->close();

if (!$report) {
    setFlash('danger', 'Report not found.');
    header("Location: performance_report.php");
    exit;
}

include __DIR__ . '/../includes/header.php';
include __DIR__ . '/../includes/sidebar.php';
?>

<div class="page-header">
    <h4><i class="fas fa-file-alt"></i> <?php echo htmlspecialchars($report['report_title']); ?></h4>
    <div style="display:flex;gap:8px;">
        <button onclick="window.print()" class="btn btn-primary"><i class="fas fa-print"></i> Print / Save PDF</button>
        <a href="performance_report.php" class="btn btn-outline"><i class="fas fa-arrow-left"></i> Back</a>
    </div>
</div>

<div class="card-box report-printable">
    <div style="margin-bottom:10px;color:var(--text-secondary);font-size:12px;">
        Generated by: <?php echo htmlspecialchars($report['generated_by_name'] ?? 'System'); ?>
        &mdash; <?php echo date('d M Y, h:i A', strtotime($report['created_at'])); ?>
    </div>
    <?php
    // Sanitize stored HTML — allow only safe tags/attributes for report display
    $allowedTags = '<h1><h2><h3><h4><h5><h6><p><br><hr><div><span><table><thead><tbody><tr><th><td><strong><em><b><i><small><ul><ol><li><img><canvas><style>';
    echo strip_tags($report['report_html'], $allowedTags);
    ?>
</div>

<?php include __DIR__ . '/../includes/footer.php'; ?>
